package ro.bull.bpm.examples.loan;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Loan Application")
public class LoanApplication  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Float rate;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Float income;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer period;

    public LoanApplication() {
    }

    public LoanApplication(java.lang.Integer age, java.lang.Float rate, java.lang.Integer period, java.lang.Float income) {
        this.age = age;
        this.rate = rate;
        this.period = period;
        this.income = income;
    }


    
    public java.lang.Float getRate() {
        return this.rate;
    }

    public void setRate(  java.lang.Float rate ) {
        this.rate = rate;
    }
    
    public java.lang.Float getIncome() {
        return this.income;
    }

    public void setIncome(  java.lang.Float income ) {
        this.income = income;
    }
    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(  java.lang.Integer age ) {
        this.age = age;
    }
    
    public java.lang.Integer getPeriod() {
        return this.period;
    }

    public void setPeriod(  java.lang.Integer period ) {
        this.period = period;
    }




}
