package ro.bull.bpm.examples.loan;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.workbench.common.services.datamodeller.annotations.Label(value = "Eligible")
public class Eligible  implements java.io.Serializable {

static final long serialVersionUID = 1L;

    public Eligible() {
    }








}